openapi: 3.0.1
# https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html
info:
  title: Cloud Resume API v1
  description: Cloud Resume API v1
  version: 1.0.0
servers:
  - url: ${domain_name}
paths:
  /views-count:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: ${get_views_count_lambda_arn}
        credentials: ${get_views_count_lambda_iam_role_arn}
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                    description: Count of views
        "500":
          description: ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                  exception:
                    type: string
                    description: Error exception
