---
- name: Play for deploying S3 files and invalidating CloudFront cache
  hosts: localhost
  connection: local

  vars:
    s3_files_dir: "{{ s3_files_dir }}"
    s3_bucket_name: "{{ s3_bucket_name }}"
    cloudfront_distribution_id: "{{ cloudfront_distribution_id }}"

  tasks:
    - name: Synchronize directory contents to S3 bucket
      community.aws.s3_sync:
        bucket: "{{ s3_bucket_name }}"
        file_root: "{{ s3_files_dir }}"
        permission: "public-read"
        delete: true

    - name: Create CloudFront invalidations
      community.aws.cloudfront_invalidation:
        distribution_id: "{{ cloudfront_distribution_id }}"
        target_paths:
          - /*
