---
- name: Play for retrieving aws credentials
  hosts: localhost

  vars:
    s3_files_path: "{{ s3_files_path }}"
    s3_bucket_name: "{{ project_name }}"

  tasks:
    - name: Synchronize directory contents to S3 bucket
      community.aws.s3_sync:
        bucket: "{{ s3_bucket_name }}"
        file_root: "{{ s3_files_path }}"
        permission: "public-read"
        delete: true
