---
- name: Play for uploading terraform tfstate files to s3 bucket
  hosts: localhost
  connection: local

  vars:
    # outside vars
    project_base_dir: "{{ project_base_dir }}"
    terraform_env: "{{ terraform_env }}"

    # local vars
    s3_bucket_name: "avivilloz-tffiles"
    terraform_dir: "{{ project_base_dir }}/infra/terraform"

  tasks:
    - name: Download terraform tf files
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket_name }}"
        object: "{{ terraform_env }}.{{ item.file_type }}"
        src: "{{ terraform_dir }}/terraform.{{ item.file_type }}"
        overwrite: true
        mode: put
      with_items:
        - file_type: "tfstate"
        - file_type: "tfvars"
