---
- name: Play for downloading terraform tf files from s3 bucket
  hosts: localhost
  connection: local

  vars:
    # outside vars
    project_base_dir: "{{ project_base_dir }}"
    terraform_env: "{{ terraform_env }}"

    # local vars
    terraform_dir: "{{ project_base_dir }}/infra/terraform"
    s3_bucket_name: "avivilloz-tffiles"

  tasks:
    # - name: Install required python libraries
    #   ansible.builtin.pip:
    #     name:
    #       - boto3==1.34.151
    #       - botocore==1.34.151

    - name: Upload terraform tf files
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket_name }}"
        object: "{{ terraform_env }}.{{ item.file_type }}"
        dest: "{{ terraform_dir }}/terraform.{{ item.file_type }}"
        mode: get
      with_items:
        - file_type: "tfstate"
        - file_type: "tfvars"
