---
- name: Play for uploading terraform tfstate files to s3 bucket
  hosts: localhost
  connection: local

  vars:
    # outside vars
    project_base_dir: "../.."

    # local vars
    s3_bucket_name: "cloudres_tfstates"
    s3_buckets_dir: "{{ project_base_dir }}/temp/s3_buckets"
    s3_bucket_sync_dir: "{{ s3_buckets_dir }}/{{ s3_bucket_name }}"
    tf_envs_dir: "{{ project_base_dir }}/infra/terraform/environments"

  tasks:
    - name: Create s3_tfstates_bucket_sync dir
      ansible.builtin.file:
        state: directory
        path: "{{ s3_bucket_sync_dir }}"
        mode: "0755"

    - name: Copy s3 files to s3_tfstates_bucket_sync dir
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0755"
      with_items:
        - src: "{{ terraform_environments_dir }}/production/terraform.tfstate"
          dest: "{{ s3_bucket_sync_dir }}/production.tfstate"
        - src: "{{ terraform_environments_dir }}/integration/terraform.tfstate"
          dest: "{{ s3_bucket_sync_dir }}/integration.tfstate"
        - src: "{{ terraform_environments_dir }}/backend/terraform.tfstate"
          dest: "{{ s3_bucket_sync_dir }}/backend.tfstate"

    - name: Synchronize directory contents to S3 bucket
      community.aws.s3_sync:
        bucket: "{{ s3_bucket_name }}"
        file_root: "{{ s3_bucket_sync_dir }}"
        permission: "public-read"
        delete: true
