name: Build docker images

on:
  workflow_call:
    inputs:
      DOCKERFILE_PATH:
        type: string
        required: true
      DOCKER_IMAGE:
        type: string
        required: true

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

    outputs:
      DOCKER_IMAGE: 
        value: ${{ inputs.DOCKER_IMAGE }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./${{ inputs.DOCKERFILE_PATH }}
          tags: ${{ inputs.DOCKER_IMAGE }}
