name: Test and deploy on dev push

on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-deploy-docker-image:
    uses: ./.github/workflows/build_docker_image.yaml
    with:
      DOCKERFILE_PATH: ./infra/Dockerfile
      DOCKER_IMAGE: avivilloz/cloud-resume:deploy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dev-env-setup:
    needs: [build-deploy-docker-image]
    uses: ./.github/workflows/deploy.yaml
    with:
      TERRAFORM_ENV: development
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      DOCKER_IMAGE: ${{ needs.build-deploy-docker-image.outputs.DOCKER_IMAGE }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  modified-dir-detection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@master
        id: modified-dir-detection
        with:
          filters: |
            FRONTEND:
              - 'frontend/**'
            BACKEND:
              - 'backend/**'  
    outputs:
      FRONTEND: ${{ steps.modified-dir-detection.outputs.FRONTEND }}
      BACKEND: ${{ steps.modified-dir-detection.outputs.BACKEND }}

  backend-tests:
    needs: [dev-env-setup, modified-dir-detection]
    uses: ./.github/workflows/test.yaml
    if: ${{ needs.modified-dir-detection.outputs.BACKEND == 'true' }}
    with:
      LAB: "backend"
      PYTEST_ARGS: "--api-url=${{ needs.dev-env-setup.outputs.API_URL }}"
      DOCKER_IMAGE: avivilloz/cloud-resume:test-backend
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  frontend-tests:
    needs: [dev-env-setup, modified-dir-detection]
    uses: ./.github/workflows/test.yaml
    if: ${{ needs.modified-dir-detection.outputs.FRONTEND == 'true' }}
    with:
      LAB: "frontend"
      PYTEST_ARGS: "--website-url=${{ needs.dev-env-setup.outputs.WEBSITE_URL }}"
      DOCKER_IMAGE: avivilloz/cloud-resume:test-frontend
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  website-deployment:
    needs: [build-deploy-docker-image, backend-tests, frontend-tests]
    uses: ./.github/workflows/deploy.yaml
    with:
      TERRAFORM_ENV: production
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      DOCKER_IMAGE: ${{ needs.build-deploy-docker-image.outputs.DOCKER_IMAGE }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}