name: Test and deploy website

on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  path-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@master
        id: path-changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'  
    outputs:
      frontend: ${{ steps.path-changes.outputs.frontend }}
      backend: ${{ steps.path-changes.outputs.backend }}

  dev-env-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/workflows/deploy.yml
        id: deploy
        with:
            TERRAFORM_ENV: development
    outputs:
      API_URL: ${{ steps.deploy.outputs.API_URL }}
      WEBSITE_URL: ${{ steps.deploy.outputs.WEBSITE_URL }}

  backend-tests:
    needs: [dev-env-setup, path-changes]
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR_MODIFIED: ${{ needs.path-changes.outputs.frontend }}
      API_URL: ${{ needs.dev-env-setup.outputs.API_URL }}
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/workflows/test.yml
        if: ${{ env.BACKEND_DIR_MODIFIED == 'true' }}
        with:
            LAB: "backend"
            PYTEST_ARGS: "--api-url=${{ env.API_URL }}"

  frontend-tests:
    needs: [dev-env-setup, path-changes]
    runs-on: ubuntu-latest
    env:
      FRONTEND_DIR_MODIFIED: ${{ needs.path-changes.outputs.frontend }}
      WEBSITE_URL: ${{ needs.dev-env-setup.outputs.WEBSITE_URL }}
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/workflows/test.yml
        if: ${{ env.FRONTEND_DIR_MODIFIED == 'true' }}
        with:
            LAB: "frontend"
            PYTEST_ARGS: "--website-url=${{ env.WEBSITE_URL }}"

  website-deployment:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/workflows/deploy.yml
        with:
            TERRAFORM_ENV: production