name: Template

on:
  push:
    branches: [master]
    paths:
      - 'template/**'

jobs:
  template-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Template
        run: | 
          echo "This is just a template"