name: Run Tests

on:
  workflow_call:
    inputs:
        LAB:
            type: string
            required: true
        PYTEST_ARGS:
            type: string
            required: true
        SHOULD_RUN:
            type: string
            required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      LAB_DIR: "tests/${{ inputs.LAB }}"

    steps:
      - uses: actions/checkout@master
        if: ${{ inputs.SHOULD_RUN == 'true' }}
      - name: Setup venv, install requirements and run tests
        if: ${{ inputs.SHOULD_RUN == 'true' }}
        run: |
          docker build -t test ${{ env.LAB_DIR }}
          docker run test ${{ inputs.PYTEST_ARGS }}
