name: Test github workflow

on:
  push:
    branches: [master]
    paths:
      - '.github/**'
      - 'tests/**'

jobs:
  test-docker:
    runs-on: ubuntu-latest
    env:
        LAB_DIR: tests/backend/
    steps:
      - uses: actions/checkout@master
      - name: Test Docker
        run: | 
          docker build -t test ${{ env.LAB_DIR }}
          docker run test --api-url="https://resume-dev-api.avivilloz.com"