name: Run Tests

on:
  workflow_call:
    inputs:
        LAB:
            type: string
            required: true
        PYTEST_ARGS:
            type: string
            required: true
        SHOULD_RUN:
            type: string
            required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      LAB_DIR: "tests/${{ inputs.LAB }}"

    steps:
      - uses: actions/checkout@master
        if: ${{ inputs.SHOULD_RUN == 'true' }}

      - name: Build docker image with tests requirements
        if: ${{ inputs.SHOULD_RUN == 'true' && success() }}
        run: docker build -t test ${{ env.LAB_DIR }}

      - name: Run tests in docker container
        if: ${{ inputs.SHOULD_RUN == 'true' && success() }}
        run: docker run test ${{ inputs.PYTEST_ARGS }}
