name: Test docker infra

on:
  push:
    branches: [master]
    paths:
      - 'infra/**'
      - '.github/**'

jobs:
  template-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build docker image
        run: docker build -t test infra

      - name: Run docker container
        run: docker run test