name: Run Tests

on:
  workflow_call:
    inputs:
      LAB:
        type: string
        required: true
      PYTEST_ARGS:
        type: string
        required: true
      DOCKER_IMAGE:
        type: string
        required: true
      
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-docker-image:
    uses: ./.github/workflows/build_docker_image.yaml
    with:
      DOCKERFILE_PATH: tests/${{ inputs.LAB }}/Dockerfile
      DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  run-tests:
    needs: [build-docker-image]
    runs-on: ubuntu-latest
    container: ${{ inputs.DOCKER_IMAGE }}

    env:
      TESTS_DIR: "tests/${{ inputs.LAB }}/tests"

    steps:
      - uses: actions/checkout@v3

      - name: Run tests in docker container
        run: pytest -s ${{ env.TESTS_DIR }}/tests ${{ inputs.PYTEST_ARGS }}