name: Run Tests

on:
  workflow_call:
    inputs:
        LAB:
            type: string
            required: true
        PYTEST_ARGS:
            type: string
            required: true
        SHOULD_RUN:
            type: string
            required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      TESTS_DIR: "tests/${{ inputs.LAB }}"
      VENV_NAME: "venv"

    steps:
      - uses: actions/checkout@master
        if: ${{ inputs.SHOULD_RUN == 'true' }}
      - name: Setup venv, install requirements and run tests
        if: ${{ inputs.SHOULD_RUN == 'true' }}
        run: |
          python -m venv ${{ env.VENV_NAME }}
          . ${{ env.VENV_NAME }}/bin/activate
          pip install -r ${{ env.TESTS_DIR }}/requirements.txt
          pytest -s ${{ env.TESTS_DIR }} ${{ inputs.PYTEST_ARGS }}
