name: Run Tests

on:
  workflow_call:
    inputs:
      LAB:
        type: string
        required: true
      PYTEST_ARGS:
        type: string
        required: true
      DOCKER_IMAGE:
        type: string
        required: true
      
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-docker-image:
    uses: ./.github/workflows/build_docker_image.yaml
    with:
      DOCKERFILE_PATH: tests/${{ inputs.LAB }}/Dockerfile
      DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  run-tests:
    needs: [build-docker-image]
    runs-on: ubuntu-latest
    container: ${{ inputs.DOCKER_IMAGE }}

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      LAB_DIR: "tests/${{ inputs.LAB }}"

    steps:
      - uses: actions/checkout@master

      - name: Run tests
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r ${{ env.LAB_DIR }}/requirements.txt
          pytest -s ${{ env.LAB_DIR }}/tests ${{ inputs.PYTEST_ARGS }}