name: Test docker infra

on:
  push:
    branches: [master]
    paths:
      - 'infra/**'
      - '.github/**'

jobs:
  template-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # - name: Build docker image
      #   run: docker build -t test infra

      # - name: Run docker container
      #   run: docker run test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./infra/Dockerfile
          tags: avivilloz/cloud-resume-deploy:latest