name: Run Tests

on:
  workflow_call:
    inputs:
      LAB:
        type: string
        required: true
      PYTEST_ARGS:
        type: string
        required: true
      DOCKER_IMAGE:
        type: string
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: ${{ inputs.DOCKER_IMAGE }}

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      TESTS_DIR: "tests/${{ inputs.LAB }}/tests"

    steps:
      - uses: actions/checkout@v3

      - name: Run tests in docker container
        run: pytest -s ${{ env.TESTS_DIR }} ${{ inputs.PYTEST_ARGS }}